# Generated by Django 3.2.5 on 2021-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0004_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cupon',
            field=models.BooleanField(default=False),
        ),
    ]
